### ISSUE TITLE
panic while restarting data transfer channel

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/go-data-transfer#150]
```
echo: http: panic serving 127.0.0.1:60396: runtime error: invalid memory address or nil pointer dereference
goroutine 3531 [running]:
net/http.(*conn).serve.func1(0xc000cfa140)
	/usr/lib/go/src/net/http/server.go:1824 +0x153
panic(0x26cff40, 0x504b620)
	/usr/lib/go/src/runtime/panic.go:971 +0x499
github.com/filecoin-project/go-data-transfer/channels.channelState.Voucher(0xc00409b7a0, 0x26, 0x16, 0xc00409b8c0, 0x22, 0xc004096a50, 0xc00409b920, 0x26, 0xc00409b980, 0x26, ...)
	/home/why/go/pkg/mod/github.com/filecoin-project/go-data-transfer@v1.2.7/channels/channel_state.go:93 +0x5a
github.com/filecoin-project/go-data-transfer/impl.(*manager).openPushRestartChannel(0xc000424780, 0x2d17d70, 0xc000044c50, 0x2d35898, 0xc0040d01c0, 0xc003e402d0, 0x26)
	/home/why/go/pkg/mod/github.com/filecoin-project/go-data-transfer@v1.2.7/impl/restart.go:85 +0x83
github.com/filecoin-project/go-data-transfer/impl.(*manager).RestartDataTransferChannel(0xc000424780, 0x2d17d70, 0xc000044c50, 0xc003e40270, 0x26, 0xc003e402d0, 0x26, 0x16, 0x1c, 0x60)
	/home/why/go/pkg/mod/github.com/filecoin-project/go-data-transfer@v1.2.7/impl/impl.go:472 +0x313
github.com/whyrusleeping/estuary/filclient.(*FilClient).CheckOngoingTransfer(0xc000f9dce0, 0x2d17d70, 0xc000044c50, 0xc0010af8fd, 0x3, 0xc0016cb3b0, 0x0, 0x0)
	/home/why/code/estuary/filclient/filclient.go:567 +0xfb
main.(*Server).checkDeal(0xc000ffb470, 0xc000cd2a50, 0xc000cce601, 0x0, 0x0)
	/home/why/code/estuary/main.go:928 +0xb2e
main.(*Server).EnsureStorage(0xc000ffb470, 0xc000cc03c0, 0x22, 0x22, 0x0)
	/home/why/code/estuary/main.go:808 +0x449
```

**Comment by whyrusleeping** [comment]
Got a similar panic while doing nothing, I think it was the background transfer restarter: 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x105015a]

goroutine 593124 [running]:
github.com/filecoin-project/go-data-transfer/channels.channelState.Voucher(0xc0184e9b00, 0x26, 0x19, 0xc0184e9c50, 0x22, 0xc0155884c8, 0xc0184e9cb0, 0x26, 0xc0184e9d10, 0x26, ...)
	/home/why/go/pkg/mod/github.com/filecoin-project/go-data-transfer@v1.2.7/channels/channel_state.go:93 +0x5a
github.com/filecoin-project/go-data-transfer/impl.(*manager).openPushRestartChannel(0xc000424780, 0x2d18db8, 0xc012750a80, 0x2d36918, 0xc018aee9a0, 0xc018499f50, 0x26)
	/home/why/go/pkg/mod/github.com/filecoin-project/go-data-transfer@v1.2.7/impl/restart.go:85 +0x83
github.com/filecoin-project/go-data-transfer/impl.(*manager).RestartDataTransferChannel(0xc000424780, 0x2d18db8, 0xc012750a80, 0xc00072e720, 0x26, 0xc018499f50, 0x26, 0x19, 0x0, 0x0)
	/home/why/go/pkg/mod/github.com/filecoin-project/go-data-transfer@v1.2.7/impl/impl.go:472 +0x313
github.com/filecoin-project/go-data-transfer/pushchannelmonitor.(*monitoredChannel).restartChannel(0xc017a27ee0)
	/home/why/go/pkg/mod/github.com/filecoin-project/go-data-transfer@v1.2.7/pushchannelmonitor/pushchannelmonitor.go:319 +0x48a
created by github.com/filecoin-project/go-data-transfer/pushchannelmonitor.(*monitoredChannel).checkDataRate
	/home/why/go/pkg/mod/github.com/filecoin-project/go-data-transfer@v1.2.7/pushchannelmonitor/pushchannelmonitor.go:282 +0x53f
```

**Comment by whyrusleeping** [comment]
As per @hannahhoward's suggestion, adding the following to my code: 

```go
	err = dataTransfer.RegisterVoucherType(&requestvalidation.StorageDataTransferVoucher{}, nil)
	if err != nil {
		return nil, err
	}
```

**Comment by hannahhoward** [comment]
There is a design issue here though: the Voucher method should return an error type.
