### ISSUE TITLE
Go routine deadlock in go-data-transfer Graphsync transport over dataLock Mutex

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/go-data-transfer#192]
As submitted by @whyrusleeping , it seems there is a potential deadlock with the `dataLock` mutex on the transport implementation for Graphsync in go-data-transfer.

Go routine dump attached.
[estuary-goros-hang.zip](https://github.com/filecoin-project/go-data-transfer/files/6275415/estuary-goros-hang.zip)

**Comment by dirkmc** [comment]
```
goroutine 232 [semacquire, 692 minutes]:
sync.runtime_SemacquireMutex(0xc00012a634, 0x2ab6600, 0x1)
	/usr/local/go/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc00012a630)
	/usr/local/go/src/sync/mutex.go:138 +0x105
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:81
sync.(*RWMutex).Lock(0xc00012a630)
	/usr/local/go/src/sync/rwmutex.go:111 +0x90
github.com/filecoin-project/go-data-transfer/transport/graphsync.(*Transport).gsReqRecdHook(0xc00012a600, 0xc002b6a5a0, 0x26, 0x2f98ee0, 0xc00330ac80, 0x2f97590, 0xc0077a6230)
	/home/why/go/pkg/mod/github.com/filecoin-project/go-data-transfer@v1.4.1/transport/graphsync/graphsync.go:533 +0x2fc
github.com/ipfs/go-graphsync/responsemanager/hooks.requestHookDispatcher(0x29b7960, 0xc01a353e90, 0x28d8ec0, 0xc00032cfd0, 0x0, 0x0)
	/home/why/go/pkg/mod/github.com/ipfs/go-graphsync@v0.6.0/responsemanager/hooks/requesthook.go:34 +0xfb
github.com/hannahhoward/go-pubsub.(*PubSub).Publish(0xc00095cb40, 0x29b7960, 0xc01a353e90, 0x0, 0x0)
	/home/why/go/pkg/mod/github.com/hannahhoward/go-pubsub@v0.0.0-20200423002714-8d62886cc36e/pubsub.go:76 +0xd0
github.com/ipfs/go-graphsync/responsemanager/hooks.(*IncomingRequestHooks).ProcessRequestHooks(0xc0005a46c0, 0xc002b6a5a0, 0x26, 0x2f98ee0, 0xc00330ac80, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/why/go/pkg/mod/github.com/ipfs/go-graphsync@v0.6.0/responsemanager/hooks/requesthook.go:66 +0x127
github.com/ipfs/go-graphsync/responsemanager.(*queryExecutor).prepareQuery(0xc00013d050, 0x2f8d1f8, 0xc00330ac40, 0xc002b6a5a0, 0x26, 0xc00a1c77d0, 0x22, 0x2faaef8, 0xc0035eade0, 0x1200000000, ...)
	/home/why/go/pkg/mod/github.com/ipfs/go-graphsync@v0.6.0/responsemanager/queryexecutor.go:116 +0xf6
github.com/ipfs/go-graphsync/responsemanager.(*queryExecutor).executeTask(0xc00013d050, 0xc002b6a5a0, 0x26, 0x12, 0x0, 0xc01a353dd0, 0x2f8d1f8, 0xc00330ac40, 0xc00a1c77d0, 0x22, ...)
	/home/why/go/pkg/mod/github.com/ipfs/go-graphsync@v0.6.0/responsemanager/queryexecutor.go:97 +0x1f0
github.com/ipfs/go-graphsync/responsemanager.(*queryExecutor).processQueriesWorker(0xc00013d050)
	/home/why/go/pkg/mod/github.com/ipfs/go-graphsync@v0.6.0/responsemanager/queryexecutor.go:75 +0x5e5
created by github.com/ipfs/go-graphsync/responsemanager.(*ResponseManager).run
	/home/why/go/pkg/mod/github.com/ipfs/go-graphsync@v0.6.0/responsemanager/responsemanager.go:301 +0x90
```

**Comment by dirkmc** [comment]
Fixed by https://github.com/filecoin-project/go-data-transfer/pull/199

Specifically:
https://github.com/filecoin-project/go-data-transfer/pull/199/files#diff-ef4bcba1f2d11506278385f0dd22312705002145b9c930293ede611798ad4ed9L378-R389
